version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/excel
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data



volumes:
  pg_data: { }

