# Generated by Django 4.2.5 on 2023-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(blank=True),
        ),
    ]
