# Generated by Django 4.2.5 on 2023-10-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_sheet_name_alter_cell_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='name',
            field=models.CharField(default='Default cell'),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('name', 'sheet')},
        ),
    ]
