# Generated by Django 4.2.5 on 2023-10-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_alter_cell_name_alter_cell_value_alter_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='excel.sheet'),
        ),
    ]
